apiVersion: v1
kind: ConfigMap
metadata:
  name: bifrost-backup-config
data:
  bifrost_backups.yaml: |-
    version: "1.0"
    databases:
    - database_type: 2
      name: ""
      sqlite3:
        path: .
      storages:
        - default
      cron: 0,30 * * * *
    storages:
    - storage_type: 1
      name: default
      cypher_key: <EXAMPLE-REPACE-ME-!>
      retention_days: 21
      compression: false
      local_storage:
        folderpath: /app/.bifrost-backups
---
apiVersion: batch/v1
kind: Job
metadata:
  name: bifrost-backup-job
spec:
  template:
    metadata:
      name: bifrost-backup-pod
    spec:
      containers:
      - name: bifrost-backup
        image: ghcr.io/martient/bifrost-backups:1.3.1
        command: ["./bifrost-backup", "backup", "no-encryption", "--disable-update-check"]  # Adjust the command as needed
        volumeMounts:
        - name: bifrost-backup-config
          mountPath: /etc/bifrost-backup
        - name: bifrost-backup-home
          mountPath: /root/.config
      restartPolicy: OnFailure
      volumes:
      - name: bifrost-backup-config
        configMap:
          name: bifrost-backup-config
      - name: bifrost-backup-home
        emptyDir: {}
---