name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ '**' ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dagger/dagger-for-github@v6.13.0
        with:
          version: "0.9.3"
      - name: Run test
        run: dagger call test --source=.
      - name: Run release
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            dagger call release --source=.
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
