name: CI

on:
  pull_request:
  push:
    # run only against tags
    tags:
      - "*"

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
            go-version: stable
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Install Dagger
        uses: dagger/dagger-for-github@v6
        with:
          version: "0.13.5"  # Specify the desired Dagger version
      - name: Run Dagger pipeline
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dagger call test --source=.
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      # More assembly might be required: Docker logins, GPG, etc.
      # It all depends on your needs.
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}