name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]

jobs:
  tests:
    strategy:
      matrix:
        go_version: [ 1.20.x ]

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}

    - name: Set up gotestfmt
      uses: GoTestTools/gotestfmt-action@v2
      with:
        version: v2.0.0
        org: GoTestTools
        repo: gotestfmt

    - name: Test
      run: go test -race -json -v -coverprofile=coverage.txt ./... 2>&1 | tee /tmp/gotest.log | gotestfmt